events {
    worker_connections 1024;
}

http {
    upstream blazecache_cluster {
        server blazecache-1:6784;
        server blazecache-2:6784;
        server blazecache-3:6784;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://blazecache_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
